// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: user.
// - Entity ID: 102019b61ef48c47062a3d199b3f8c1fab9.
// - Entity Version: 102019b629eb0ac764dae2f9583407618e2.
// - Task ID: 69508ad312e93c1a0f4bc3a3.
// - Task Root ID: 69505d82ff5145db4db85a3f.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";










/**
 * Interface for UserModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface UserModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  username: string;
  password_hash: string;
  coin: number;
  is_admin: boolean;
}

/**
 * ORM class for User entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class UserORM {
  private static instance: UserORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019b61ef48c47062a3d199b3f8c1fab9';
    this.entityName = 'user';
    this.entityVersion = '102019b629eb0ac764dae2f9583407618e2';
    this.taskId = '69508ad312e93c1a0f4bc3a3';
    this.taskRootId = '69505d82ff5145db4db85a3f';
  }

  /**
   * Get singleton instance of UserORM
   */
  public static getInstance(): UserORM {
    if (!UserORM.instance) {
      UserORM.instance = new UserORM();
    }
    
    return UserORM.instance;
  }

  /**
   * Get user by IDs
   * Use this as a batch operation to get multiple records at once.
   */
  async getUserByIDs(ids: string[]): Promise<UserModel[]> {
    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete user by IDs
   * Use this as a batch operation to delete multiple records at once.
   */
  async deleteUserByIDs(ids: string[]): Promise<void> {
    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });
  }

  /**
   * Get all User records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllUser(): Promise<UserModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new User record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertUser(data: UserModel[]): Promise<UserModel[]> {
    // Prepare structured values but exclude read-only empty fields to avoid inserting empty strings into DB
    const structured = data.map((item) => {
      const vals = UserModelToValues(item).filter((v) => {
        if (!v.name) return false;
        if (["id", "data_creator", "data_updater", "create_time", "update_time"].includes(v.name) && (v.string === "" || v.string === undefined || v.string === null)) return false;
        return true;
      });
      // Ensure coin is numeric
      for (const val of vals) {
        if (val.name === 'coin') {
          if (val.number === undefined || val.number === null) {
            val.number = 0;
            val.string = '0';
          }
        }
      }
      return CreateData(vals);
    });

    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all User records
   */
  async purgeAllUser(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List User records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listUser(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[UserModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get user by Id index
   * This function gets data by index.
   */
  async getUserById(
    id: string,
  ): Promise<UserModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) user by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setUserById(
    id: string,
    data: UserModel
  ): Promise<UserModel[]> {
    const index = createIndexId(
      id
    );

    const values = UserModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete user by Id index
   */
  async deleteUserById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get user by DataCreator index
   * This function gets data by index.
   */
  async getUserByDataCreator(
    data_creator: string,
  ): Promise<UserModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) user by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setUserByDataCreator(
    data_creator: string,
    data: UserModel
  ): Promise<UserModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = UserModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete user by DataCreator index
   */
  async deleteUserByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get user by DataUpdater index
   * This function gets data by index.
   */
  async getUserByDataUpdater(
    data_updater: string,
  ): Promise<UserModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) user by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setUserByDataUpdater(
    data_updater: string,
    data: UserModel
  ): Promise<UserModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = UserModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete user by DataUpdater index
   */
  async deleteUserByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get user by Username index
   * This function gets data by index.
   */
  async getUserByUsername(
    username: string,
  ): Promise<UserModel[]> {
    const index = createIndexUsername(
      username
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) user by Username index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setUserByUsername(
    username: string,
    data: UserModel
  ): Promise<UserModel[]> {
    const index = createIndexUsername(
      username
    );

    const values = UserModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete user by Username index
   */
  async deleteUserByUsername(
    username: string
  ): Promise<void> {
    const index = createIndexUsername(
      username
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get user by IsAdmin index
   * This function gets data by index.
   */
  async getUserByIsAdmin(
    is_admin: boolean,
  ): Promise<UserModel[]> {
    const index = createIndexIsAdmin(
      is_admin
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) user by IsAdmin index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setUserByIsAdmin(
    is_admin: boolean,
    data: UserModel
  ): Promise<UserModel[]> {
    const index = createIndexIsAdmin(
      is_admin
    );

    const values = UserModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete user by IsAdmin index
   */
  async deleteUserByIsAdmin(
    is_admin: boolean
  ): Promise<void> {
    const index = createIndexIsAdmin(
      is_admin
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to UserModel data array
   */
  private resultToData(values: Data[]): UserModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return UserModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as UserModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized UserModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is UserModel => item !== null);
  }
}

/**
 * Convert UserModel data to Value array
 */
function UserModelToValues(data: UserModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'username', type: DataType.string, defaultValue: '' },
    { key: 'password_hash', type: DataType.string, defaultValue: '' },
    { key: 'coin', type: DataType.number, defaultValue: 0 },
    { key: 'is_admin', type: DataType.boolean, defaultValue: false },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof UserModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to UserModel data
 */
function UserModelFromValues(values: Value[]): UserModel {
  const data: Partial<UserModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'username':
        data.username = ParseValue(value, DataType.string) as string;
        break;
      case 'password_hash':
        data.password_hash = ParseValue(value, DataType.string) as string;
        break;
      case 'coin':
        data.coin = ParseValue(value, DataType.number) as number;
        break;
      case 'is_admin':
        data.is_admin = ParseValue(value, DataType.boolean) as boolean;
        break;
    }
  }
  
  return data as UserModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}
/**
 * Create index for Username fields
 */
function createIndexUsername(
  username: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, username, 'username'),
  ];

  return {
    fields: ['username'],
    values
  };
}
/**
 * Create index for IsAdmin fields
 */
function createIndexIsAdmin(
  is_admin: boolean
): Index {
  const values: Value[] = [
    CreateValue(DataType.boolean, is_admin, 'is_admin'),
  ];

  return {
    fields: ['is_admin'],
    values
  };
}

export default UserORM;