// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: coin_log.
// - Entity ID: 102019b61ef48c474dc88dc7b0c2598d956.
// - Entity Version: 102019b629eb0ac764dae2f9583407618e2.
// - Task ID: 69508ad312e93c1a0f4bc3a3.
// - Task Root ID: 69505d82ff5145db4db85a3f.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";










/**
 * Interface for CoinLogModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface CoinLogModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  user_id: string;
  amount: number;
  reason: string;
  created_at: string;
}

/**
 * ORM class for CoinLog entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class CoinLogORM {
  private static instance: CoinLogORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019b61ef48c474dc88dc7b0c2598d956';
    this.entityName = 'coin_log';
    this.entityVersion = '102019b629eb0ac764dae2f9583407618e2';
    this.taskId = '69508ad312e93c1a0f4bc3a3';
    this.taskRootId = '69505d82ff5145db4db85a3f';
  }

  /**
   * Get singleton instance of CoinLogORM
   */
  public static getInstance(): CoinLogORM {
    if (!CoinLogORM.instance) {
      CoinLogORM.instance = new CoinLogORM();
    }
    
    return CoinLogORM.instance;
  }

  /**
   * Get coin_log by IDs
   * Use this as a batch operation to get multiple records at once.
   */
  async getCoinLogByIDs(ids: string[]): Promise<CoinLogModel[]> {
    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete coin_log by IDs
   * Use this as a batch operation to delete multiple records at once.
   */
  async deleteCoinLogByIDs(ids: string[]): Promise<void> {
    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });
  }

  /**
   * Get all CoinLog records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllCoinLog(): Promise<CoinLogModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new CoinLog record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertCoinLog(data: CoinLogModel[]): Promise<CoinLogModel[]> {
    const structured = data.map((item) => CreateData(CoinLogModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all CoinLog records
   */
  async purgeAllCoinLog(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List CoinLog records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listCoinLog(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[CoinLogModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get coin_log by Id index
   * This function gets data by index.
   */
  async getCoinLogById(
    id: string,
  ): Promise<CoinLogModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) coin_log by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setCoinLogById(
    id: string,
    data: CoinLogModel
  ): Promise<CoinLogModel[]> {
    const index = createIndexId(
      id
    );

    const values = CoinLogModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete coin_log by Id index
   */
  async deleteCoinLogById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get coin_log by DataCreator index
   * This function gets data by index.
   */
  async getCoinLogByDataCreator(
    data_creator: string,
  ): Promise<CoinLogModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) coin_log by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setCoinLogByDataCreator(
    data_creator: string,
    data: CoinLogModel
  ): Promise<CoinLogModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = CoinLogModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete coin_log by DataCreator index
   */
  async deleteCoinLogByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get coin_log by DataUpdater index
   * This function gets data by index.
   */
  async getCoinLogByDataUpdater(
    data_updater: string,
  ): Promise<CoinLogModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) coin_log by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setCoinLogByDataUpdater(
    data_updater: string,
    data: CoinLogModel
  ): Promise<CoinLogModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = CoinLogModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete coin_log by DataUpdater index
   */
  async deleteCoinLogByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get coin_log by UserId index
   * This function gets data by index.
   */
  async getCoinLogByUserId(
    user_id: string,
  ): Promise<CoinLogModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) coin_log by UserId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setCoinLogByUserId(
    user_id: string,
    data: CoinLogModel
  ): Promise<CoinLogModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const values = CoinLogModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete coin_log by UserId index
   */
  async deleteCoinLogByUserId(
    user_id: string
  ): Promise<void> {
    const index = createIndexUserId(
      user_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get coin_log by CreatedAt index
   * This function gets data by index.
   */
  async getCoinLogByCreatedAt(
    created_at: string,
  ): Promise<CoinLogModel[]> {
    const index = createIndexCreatedAt(
      created_at
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) coin_log by CreatedAt index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setCoinLogByCreatedAt(
    created_at: string,
    data: CoinLogModel
  ): Promise<CoinLogModel[]> {
    const index = createIndexCreatedAt(
      created_at
    );

    const values = CoinLogModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete coin_log by CreatedAt index
   */
  async deleteCoinLogByCreatedAt(
    created_at: string
  ): Promise<void> {
    const index = createIndexCreatedAt(
      created_at
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get coin_log by CreatedAtUserId index
   * This function gets data by index.
   */
  async getCoinLogByCreatedAtUserId(
    created_at: string,
    user_id: string,
  ): Promise<CoinLogModel[]> {
    const index = createIndexCreatedAtUserId(
      created_at,
      user_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) coin_log by CreatedAtUserId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setCoinLogByCreatedAtUserId(
    created_at: string,
    user_id: string,
    data: CoinLogModel
  ): Promise<CoinLogModel[]> {
    const index = createIndexCreatedAtUserId(
      created_at,
      user_id
    );

    const values = CoinLogModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete coin_log by CreatedAtUserId index
   */
  async deleteCoinLogByCreatedAtUserId(
    created_at: string,
    user_id: string
  ): Promise<void> {
    const index = createIndexCreatedAtUserId(
      created_at,
      user_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to CoinLogModel data array
   */
  private resultToData(values: Data[]): CoinLogModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return CoinLogModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as CoinLogModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized CoinLogModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is CoinLogModel => item !== null);
  }
}

/**
 * Convert CoinLogModel data to Value array
 */
function CoinLogModelToValues(data: CoinLogModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'user_id', type: DataType.string, defaultValue: '' },
    { key: 'amount', type: DataType.number, defaultValue: 0 },
    { key: 'reason', type: DataType.string, defaultValue: '' },
    { key: 'created_at', type: DataType.string, defaultValue: '' },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof CoinLogModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to CoinLogModel data
 */
function CoinLogModelFromValues(values: Value[]): CoinLogModel {
  const data: Partial<CoinLogModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'user_id':
        data.user_id = ParseValue(value, DataType.string) as string;
        break;
      case 'amount':
        data.amount = ParseValue(value, DataType.number) as number;
        break;
      case 'reason':
        data.reason = ParseValue(value, DataType.string) as string;
        break;
      case 'created_at':
        data.created_at = ParseValue(value, DataType.string) as string;
        break;
    }
  }
  
  return data as CoinLogModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}
/**
 * Create index for UserId fields
 */
function createIndexUserId(
  user_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, user_id, 'user_id'),
  ];

  return {
    fields: ['user_id'],
    values
  };
}
/**
 * Create index for CreatedAt fields
 */
function createIndexCreatedAt(
  created_at: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, created_at, 'created_at'),
  ];

  return {
    fields: ['created_at'],
    values
  };
}
/**
 * Create index for CreatedAtUserId fields
 */
function createIndexCreatedAtUserId(
  created_at: string,
  user_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, created_at, 'created_at'),
    CreateValue(DataType.string, user_id, 'user_id'),
  ];

  return {
    fields: ['created_at', 'user_id'],
    values
  };
}

export default CoinLogORM;