// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: purchase.
// - Entity ID: 102019b61ef48c472d2af20584525bd6651.
// - Entity Version: 102019b629eb0ac764dae2f9583407618e2.
// - Task ID: 69508ad312e93c1a0f4bc3a3.
// - Task Root ID: 69505d82ff5145db4db85a3f.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";







/**
 * Enumeration for PurchaseItemType
 */
export enum PurchaseItemType {
  Unspecified = 0,
  Deck = 1,
  Staple = 2,
  Bundle = 3,
  Gacha = 4,
}



/**
 * Interface for PurchaseModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface PurchaseModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  user_id: string;
  item_name: string;
  item_type: PurchaseItemType;
  bought_at: string;
}

/**
 * ORM class for Purchase entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class PurchaseORM {
  private static instance: PurchaseORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019b61ef48c472d2af20584525bd6651';
    this.entityName = 'purchase';
    this.entityVersion = '102019b629eb0ac764dae2f9583407618e2';
    this.taskId = '69508ad312e93c1a0f4bc3a3';
    this.taskRootId = '69505d82ff5145db4db85a3f';
  }

  /**
   * Get singleton instance of PurchaseORM
   */
  public static getInstance(): PurchaseORM {
    if (!PurchaseORM.instance) {
      PurchaseORM.instance = new PurchaseORM();
    }
    
    return PurchaseORM.instance;
  }

  /**
   * Get purchase by IDs
   * Use this as a batch operation to get multiple records at once.
   */
  async getPurchaseByIDs(ids: string[]): Promise<PurchaseModel[]> {
    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete purchase by IDs
   * Use this as a batch operation to delete multiple records at once.
   */
  async deletePurchaseByIDs(ids: string[]): Promise<void> {
    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });
  }

  /**
   * Get all Purchase records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllPurchase(): Promise<PurchaseModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new Purchase record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertPurchase(data: PurchaseModel[]): Promise<PurchaseModel[]> {
    const structured = data.map((item) => CreateData(PurchaseModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all Purchase records
   */
  async purgeAllPurchase(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List Purchase records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listPurchase(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[PurchaseModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get purchase by Id index
   * This function gets data by index.
   */
  async getPurchaseById(
    id: string,
  ): Promise<PurchaseModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) purchase by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setPurchaseById(
    id: string,
    data: PurchaseModel
  ): Promise<PurchaseModel[]> {
    const index = createIndexId(
      id
    );

    const values = PurchaseModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete purchase by Id index
   */
  async deletePurchaseById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get purchase by DataCreator index
   * This function gets data by index.
   */
  async getPurchaseByDataCreator(
    data_creator: string,
  ): Promise<PurchaseModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) purchase by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setPurchaseByDataCreator(
    data_creator: string,
    data: PurchaseModel
  ): Promise<PurchaseModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = PurchaseModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete purchase by DataCreator index
   */
  async deletePurchaseByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get purchase by DataUpdater index
   * This function gets data by index.
   */
  async getPurchaseByDataUpdater(
    data_updater: string,
  ): Promise<PurchaseModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) purchase by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setPurchaseByDataUpdater(
    data_updater: string,
    data: PurchaseModel
  ): Promise<PurchaseModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = PurchaseModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete purchase by DataUpdater index
   */
  async deletePurchaseByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get purchase by UserId index
   * This function gets data by index.
   */
  async getPurchaseByUserId(
    user_id: string,
  ): Promise<PurchaseModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) purchase by UserId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setPurchaseByUserId(
    user_id: string,
    data: PurchaseModel
  ): Promise<PurchaseModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const values = PurchaseModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete purchase by UserId index
   */
  async deletePurchaseByUserId(
    user_id: string
  ): Promise<void> {
    const index = createIndexUserId(
      user_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get purchase by ItemNameUserId index
   * This function gets data by index.
   */
  async getPurchaseByItemNameUserId(
    item_name: string,
    user_id: string,
  ): Promise<PurchaseModel[]> {
    const index = createIndexItemNameUserId(
      item_name,
      user_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) purchase by ItemNameUserId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setPurchaseByItemNameUserId(
    item_name: string,
    user_id: string,
    data: PurchaseModel
  ): Promise<PurchaseModel[]> {
    const index = createIndexItemNameUserId(
      item_name,
      user_id
    );

    const values = PurchaseModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete purchase by ItemNameUserId index
   */
  async deletePurchaseByItemNameUserId(
    item_name: string,
    user_id: string
  ): Promise<void> {
    const index = createIndexItemNameUserId(
      item_name,
      user_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get purchase by ItemType index
   * This function gets data by index.
   */
  async getPurchaseByItemType(
    item_type: PurchaseItemType,
  ): Promise<PurchaseModel[]> {
    const index = createIndexItemType(
      item_type
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) purchase by ItemType index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setPurchaseByItemType(
    item_type: PurchaseItemType,
    data: PurchaseModel
  ): Promise<PurchaseModel[]> {
    const index = createIndexItemType(
      item_type
    );

    const values = PurchaseModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete purchase by ItemType index
   */
  async deletePurchaseByItemType(
    item_type: PurchaseItemType
  ): Promise<void> {
    const index = createIndexItemType(
      item_type
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get purchase by BoughtAt index
   * This function gets data by index.
   */
  async getPurchaseByBoughtAt(
    bought_at: string,
  ): Promise<PurchaseModel[]> {
    const index = createIndexBoughtAt(
      bought_at
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) purchase by BoughtAt index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setPurchaseByBoughtAt(
    bought_at: string,
    data: PurchaseModel
  ): Promise<PurchaseModel[]> {
    const index = createIndexBoughtAt(
      bought_at
    );

    const values = PurchaseModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete purchase by BoughtAt index
   */
  async deletePurchaseByBoughtAt(
    bought_at: string
  ): Promise<void> {
    const index = createIndexBoughtAt(
      bought_at
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to PurchaseModel data array
   */
  private resultToData(values: Data[]): PurchaseModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return PurchaseModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as PurchaseModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized PurchaseModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is PurchaseModel => item !== null);
  }
}

/**
 * Convert PurchaseModel data to Value array
 */
function PurchaseModelToValues(data: PurchaseModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'user_id', type: DataType.string, defaultValue: '' },
    { key: 'item_name', type: DataType.string, defaultValue: '' },
    { key: 'item_type', type: DataType.enumeration, defaultValue: 0 },
    { key: 'bought_at', type: DataType.string, defaultValue: '' },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof PurchaseModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to PurchaseModel data
 */
function PurchaseModelFromValues(values: Value[]): PurchaseModel {
  const data: Partial<PurchaseModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'user_id':
        data.user_id = ParseValue(value, DataType.string) as string;
        break;
      case 'item_name':
        data.item_name = ParseValue(value, DataType.string) as string;
        break;
      case 'item_type':
        data.item_type = ParseValue(value, DataType.enumeration) as PurchaseItemType;
        break;
      case 'bought_at':
        data.bought_at = ParseValue(value, DataType.string) as string;
        break;
    }
  }
  
  return data as PurchaseModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}
/**
 * Create index for UserId fields
 */
function createIndexUserId(
  user_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, user_id, 'user_id'),
  ];

  return {
    fields: ['user_id'],
    values
  };
}
/**
 * Create index for ItemNameUserId fields
 */
function createIndexItemNameUserId(
  item_name: string,
  user_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, item_name, 'item_name'),
    CreateValue(DataType.string, user_id, 'user_id'),
  ];

  return {
    fields: ['item_name', 'user_id'],
    values
  };
}
/**
 * Create index for ItemType fields
 */
function createIndexItemType(
  item_type: PurchaseItemType
): Index {
  const values: Value[] = [
    CreateValue(DataType.enumeration, item_type, 'item_type'),
  ];

  return {
    fields: ['item_type'],
    values
  };
}
/**
 * Create index for BoughtAt fields
 */
function createIndexBoughtAt(
  bought_at: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, bought_at, 'bought_at'),
  ];

  return {
    fields: ['bought_at'],
    values
  };
}

export default PurchaseORM;